In [2]:
l1 = ['apple','orange','grapes']
l2 = ['strawberry','pie']

l = l1 + l2
l

['apple', 'orange', 'grapes', 'strawberry', 'pie']

In [7]:
s = 'my name is mahi'
a = 'and i am learning python'

In [9]:
s + ' ' + a 

'my name is mahi and i am learning python'

In [12]:
10 * (s + ' ' + a + '. ')

'my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. my name is mahi and i am learning python. '

In [16]:
(x,y,z) = (2,6,7)

In [18]:
z

7

In [21]:
{2,4,5} == {4,2,5} # set

True

In [22]:
(2,4,5) == (4,2,5) # tuple

False

In [44]:
p = [2,4,5]
print(p)
p.append(7)

[2, 4, 5]


In [45]:
print(p)

[2, 4, 5, 7]


In [46]:
p.append(4)
print(p)

[2, 4, 5, 7, 4]


In [67]:
m ={'name':'mahi',
    'age':19,
    'occupation':'student',
    'fruits':l1,
    'dictionary':{'fvrtplace':['sylhet','jaflong'],
                  'game':['farCry','COD']}}

In [68]:
m['occupation']

'student'

In [69]:
print(m)

{'name': 'mahi', 'age': 19, 'occupation': 'student', 'fruits': ['apple', 'orange', 'grapes'], 'dictionary': {'fvrtplace': ['sylhet', 'jaflong'], 'game': ['farCry', 'COD']}}


In [61]:
superlist = [l1,23,'sksjd',m]
superlist

[['apple', 'orange', 'grapes'],
 23,
 'sksjd',
 {'name': 'mahi', 'age': 19, 'occupation': 'student'}]

In [71]:
l = [[[[l1],l1],l1],l1] + l1

In [79]:
set([2,4,5]) 

{2, 4, 5}

In [78]:
tuple([2,4,5])

(2, 4, 5)

In [92]:
M = [[2,4,6],[3,1,8],[1,2,3]]

In [93]:
M

[[2, 4, 6], [3, 1, 8], [1, 2, 3]]

In [94]:
import numpy as np
print(np.array(M))

[[2 4 6]
 [3 1 8]
 [1 2 3]]
